Go-K8s/deploy/deploy-consumer.yaml
Adds a 'queueManager' parameter to the scaler trigger
=> Add queueManager parameter to trigger

Go-K8s/README.md, Go-K8s/deploy/deploy-producer.yaml
Remove 'publisher' wording & replace with 'producer'
=> Rename to 'producer'

Go-K8s/deploy/deploy-consumer.yaml
Allow username/password from env
=> Allow username/password from env

Spring-JMS/README.md, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/globals/Constants.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/globals/data/ReplyData.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/globals/handlers/OurDestinationResolver.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/globals/handlers/OurMessageConverter.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level107/Scheduler107.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level114/MQConfiguration114.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level114/MessageConsumer114.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level114/SendMessageService114.java
Set initial state to minimise cross interference between the sample components.
=> Set initial state

Spring-JMS/README.md, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/globals/properties/MQAdminProperties.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level115/CmdRunner115.java, Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level115/MQConfiguration115.java, Spring-JMS/src/main/resources/application.properties
Sample showing queue inquire to obtain backout threshold and backout queue.
=> level 115 sample

serverless/openwhisk/README.md, serverless/openwhisk/mq-package/deploy.sh, serverless/openwhisk/mq-package/mqfunctions.yml, serverless/openwhisk/mq-package/src/mqfeed/feed.js, serverless/openwhisk/mq-package/src/mqfeed/package.json, serverless/openwhisk/mq-package/src/mqget/mqget.js, serverless/openwhisk/mq-package/src/mqget/package.json, serverless/openwhisk/mq-package/src/mqpost/mqpost.js, serverless/openwhisk/mq-package/src/mqpost/package.json, serverless/openwhisk/mq-package/src/utillib/memory.js, serverless/openwhisk/mq-package/src/utillib/mqrestapi.js, serverless/openwhisk/mq-package/src/utillib/parambuilder.js, serverless/openwhisk/mq-package/src/utillib/triggers.js, serverless/openwhisk/mq-package/undeploy.sh
OpenWhisk / IBM Cloud Function Serverless samples
=> Serverless - OpenWhisk

.gitignore, amqp-vertx/.gitignore, amqp-vertx/README.md, amqp-vertx/pom.xml, amqp-vertx/src/main/java/vertxtutorial/AmqpClientAndConnection.java, amqp-vertx/src/main/java/vertxtutorial/Receiver.java, amqp-vertx/src/main/java/vertxtutorial/Runner.java
Sample code for creating a reactive receiver application using Vert.x to communicate with IBM MQ.
=> Added Vert.x AMQP tutorial code

container/queuemanager/compose/README.md
List the policies that we used to deploy a QueueManager to AWS ECS.
=> AWS Policy list

JMS/README.md, JMS/com/ibm/mq/samples/jms/JmsGet.java, JMS/com/ibm/mq/samples/jms/RequestCalc.java, JMS/com/ibm/mq/samples/jms/SampleEnvSetter.java, JMS/pom.xml
Update JMS samples to make use of same JSON library that allclient uses.
=> JSON alignment with all client

transactions/JMS/SE/README.md
I've updated the stale links using ibm.biz links as discussed
=> updated stale links in transactions README

ibm-messaging-mq-cloud-showcase-app/backend/AWS-showcase-backend/package.json
Align node engine requirement in package.json with version in DockerFile.
=> bump engine requirement in package.json

serverless/openwhisk/mq-package/src/mqpost/package.json
Bump Axios dependancies to min of 1.6.0
=> Bump Axios Dependency

container/queuemanager/terraform-aws/README.md, container/queuemanager/terraform-aws/multi-step-with-efs/01-vpc/main.tf, container/queuemanager/terraform-aws/multi-step-with-efs/01-vpc/platform.tf, container/queuemanager/terraform-aws/multi-step-with-efs/01-vpc/variables.tf, container/queuemanager/terraform-aws/multi-step-with-efs/02-efs/efs.tf, container/queuemanager/terraform-aws/multi-step-with-efs/02-efs/platform.tf, container/queuemanager/terraform-aws/multi-step-with-efs/02-efs/variables.tf, container/queuemanager/terraform-aws/multi-step-with-efs/03-mq-init/main.tf, container/queuemanager/terraform-aws/multi-step-with-efs/03-mq-init/platform.tf, container/queuemanager/terraform-aws/multi-step-with-efs/03-mq-init/variables.tf, container/queuemanager/terraform-aws/multi-step-with-efs/04-mq-qmgr/main.tf, container/queuemanager/terraform-aws/multi-step-with-efs/04-mq-qmgr/platform.tf, container/queuemanager/terraform-aws/multi-step-with-efs/04-mq-qmgr/variables.tf
Updates to allow multiple simultaneous usage of a shared AWS account. A name prefix has been added to the variables to overcome name clashes.
=> Terraform updates

ibm-messaging-mq-cloud-showcase-app/README.md
Changed the compose file name for deploying the containers locally.
=> Updated Readme

ibm-messaging-mq-cloud-showcase-app/docker-compose.yaml, ibm-messaging-mq-cloud-showcase-app/frontend/Dockerfile, ibm-messaging-mq-cloud-showcase-app/frontend/nginx.conf.proxy.template, ibm-messaging-mq-cloud-showcase-app/frontend/nginx.conf.template
Created a new nginx template and serving the template based on env variable using docker-entrypoint script.
=> Added proxy and redirect handling in showcaseApp

Node.js/basicput.js, Node.js/test/basicput.test.js
- Added tests for `basicput.js`
- Avoided duplicate function testing such as `ccdtCheck` function, `connx` function, `buildMQDetails` function etc.
=> Added tests for basicput.js

JMS/com/ibm/mq/samples/jms/JmsPut.java, JMS/com/ibm/mq/samples/jms/JwtHelper.java, JMS/com/ibm/mq/samples/jms/SampleEnvSetter.java, env.json
1. Modified env.json with JWT_ENDPOINTS.
2. Changes in SampleEnvSetter to populate the jwtEndpoints.
3. Added JwtHelper class for all http request related code.
4. Changes in JmsPut to handle Jwt_endpoints.
=> JWT ENABLED JMSPUT

JMS/com/ibm/mq/samples/jms/JmsGet.java, JMS/com/ibm/mq/samples/jms/JmsPub.java, JMS/com/ibm/mq/samples/jms/JmsRequest.java, JMS/com/ibm/mq/samples/jms/JmsResponse.java, JMS/com/ibm/mq/samples/jms/JmsSub.java
All stand alone have been updated to use JWT .
The logic is very much similar to JmsPut.
=> JWT ENABLED ALL STANDALONE SAMPLES

backstage/templates/dotnet-steps.yaml, backstage/templates/go-steps.yaml, backstage/templates/inputparams.yaml, backstage/templates/jms-steps.yaml, backstage/templates/node-steps.yaml, backstage/templates/python-steps.yaml, backstage/templates/repo-def.yaml, backstage/templates/spring-steps.yaml
Cleaning up repository list to allow repo picker to function correctly.
=> Make github.com default repo

README.md
Add guide to how env.json and environment variables are used to configure the sample applications in this repository
=> clarification on use of env.json file by the samples

amqp-qpid/qpid-standard/README.md, amqp-qpid/qpid-standard/pom.xml, amqp-qpid/qpid-standard/src/main/java/com/ibm/mq/samples/jms/qpid/BaseJMS20.java, amqp-qpid/qpid-standard/src/main/java/com/ibm/mq/samples/jms/qpid/BrowseJMS20.java, amqp-qpid/qpid-standard/src/main/java/com/ibm/mq/samples/jms/qpid/GetJMS20.java, amqp-qpid/qpid-standard/src/main/java/com/ibm/mq/samples/jms/qpid/Inspector.java, amqp-qpid/qpid-standard/src/main/java/com/ibm/mq/samples/jms/qpid/PutJMS20.java
Bump to Jakarta 3
Bump to Qpid Client to 2.6.1
Bump to Java Version to 17
=> Bump to QPID JMS Samples

dotnet/README.md, dotnet/connPropBuilder.cs, dotnet/dotNetPub.cs, dotnet/dotNetPut.cs, dotnet/env.cs, dotnet/ibmmq_samples.csproj
Bump to new versions of .NET and the packages
=> dotnet-anitha

C/Makefile, C/README.md, C/common.c
* Mostly clarifying some words in the README
* Update Makefile for AIX, and make it potentially easier to add more include directories
=> Minor cleanup of C JWT options
