ibm-messaging/mq-dev-patterns

- Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level102/MQConfiguration102.java
- Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level106/MQConfiguration106.java
- Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level106/MessageConsumer106.java
- Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level106/Scheduler106.java
- Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level106/SendMessageService106.java
- Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level107/MQConfiguration107.java
Level 101 uses the default out of the box template, which is ok when it is the only component in use, but this conflicted with  templates defined by the other samples.
> avoid conflicting template names

- serverless/codeengine/clientapp/mqapp.js
- serverless/codeengine/clientapp/package.json
Browser side web frameworks, like reactjs, require CORS to be enabled.
> Enable Cors in Serverless CodeEngine App

- Node.js/.npmrc
- Node.js/README.md
- Node.js/package-lock.json
- Node.js/package.json
- Remove unused jsdoc dependency. 
- Bump ibmmq dependency to latest node.js version
- Upstream dependencies require Node.js V16
> Fixes to node.js samples

- JMS/com/ibm/mq/samples/jms/ConnectionHelper.java
- JMS/com/ibm/mq/samples/jms/JmsGet.java
- JMS/com/ibm/mq/samples/jms/JmsPub.java
- JMS/com/ibm/mq/samples/jms/JmsPut.java
- JMS/com/ibm/mq/samples/jms/JmsRequest.java
- JMS/com/ibm/mq/samples/jms/JmsResponse.java
- JMS/com/ibm/mq/samples/jms/JmsSub.java
If userid is not provided in the env.json nor environment, then don't set in connection to allow bindings / no auth runtimes.
> Optional noauth in bindings mode

- .gitattributes
Added .gitattributes file to allow code source files to be correctly converted from UTF to EBCDIC when the repository is cloned onto Z systems.
> Attributes for Z

- JMS/com/ibm/mq/samples/jms/SampleEnvSetter.java
`getenv` works on Linux and MacOS to retrieve environment variables, but not on Z. `getProperty` works on all envrionments.
> Java env fix

- Node.js/basicget.js
The getMessages promise should only resolve if there are no new messages or it is not possible to retrieve more messages.
> Fix promise resolution in getMessages

- JMS/com/ibm/mq/samples/jms/ConnectionHelper.java
- JMS/com/ibm/mq/samples/jms/JmsGet.java
- JMS/com/ibm/mq/samples/jms/JmsPub.java
- JMS/com/ibm/mq/samples/jms/JmsPut.java
- JMS/com/ibm/mq/samples/jms/JmsRequest.java
- JMS/com/ibm/mq/samples/jms/JmsResponse.java
- JMS/com/ibm/mq/samples/jms/JmsSub.java
- JMS/com/ibm/mq/samples/jms/SampleEnvSetter.java
- JMS/pom.xml
Fix code issues when host and port are not provided in the environment values. These are not needed when a CCDT is in use.
> Code fixes to enable connection to a uniform cluster

- JMS/com/ibm/mq/samples/jms/ConnectionHelper.java
- JMS/com/ibm/mq/samples/jms/JmsGet.java
- JMS/com/ibm/mq/samples/jms/JmsPub.java
- JMS/com/ibm/mq/samples/jms/JmsPut.java
- JMS/com/ibm/mq/samples/jms/JmsRequest.java
- JMS/com/ibm/mq/samples/jms/JmsResponse.java
- JMS/com/ibm/mq/samples/jms/JmsSub.java
- JMS/com/ibm/mq/samples/jms/SampleEnvSetter.java
Look at the environment value for `APP_NAME`, if present use it to set the connection factory property `WMQ_APPLICATIONNAME`. If not found then use a default.
> Allow application name to be set via environment settings 

- JMS/com/ibm/mq/samples/jms/BasicConsumer.java
- JMS/com/ibm/mq/samples/jms/JmsGet.java
In the message getters add a one second wait to allow other consumers running on the same machine to receive messages.
> Yield the CPU after a get

- JMS/README.md
- JMS/com/ibm/mq/samples/jms/SampleEnvSetter.java
- JMS/pom.xml
Add a `-DEnvFile` environment setting that allows the location and name of the environment to be overridden. If not provided then the default is `../env.json`
If the file can't be found then CCDT, QMGR, QUEUE and required app credentials need to be provided as `-D` options.
> In JMS Samples allow location of env file to be overriden

- JMS/com/ibm/mq/samples/jms/ConnectionHelper.java
- JMS/com/ibm/mq/samples/jms/ConsumerHelper.java
- JMS/com/ibm/mq/samples/jms/JmsExceptionHelper.java
- JMS/com/ibm/mq/samples/jms/JmsGet.java
- JMS/com/ibm/mq/samples/jms/JmsPub.java
- JMS/com/ibm/mq/samples/jms/JmsPut.java
- JMS/com/ibm/mq/samples/jms/JmsRequest.java
- JMS/com/ibm/mq/samples/jms/JmsResponse.java
- JMS/com/ibm/mq/samples/jms/JmsSub.java
The previous code did not deal with JMSRuntimeExceptions, which meant is was very difficult when I was trying to debug connection failures with S's tests.
This makes a common part that all the relevant programs can use - there's probably more commonality possible, but this solves the primary problem.
> Add a common exception handler that also works with JMSRuntimeException

- ibm-messaging-mq-cloud-showcase-app/backend/AWS-showcase-backend/models/Requestor.js
Fix to debug message, which was throwing an exception as it was referring to an out of scope parameter.
> Fix to debug message

- ibm-messaging-mq-cloud-showcase-app/backend/Dockerfile
was throwing a "npm not found" error on be container launch.
> Fix docker file for showcase backend

- ibm-messaging-mq-cloud-showcase-app/backend/Dockerfile
Be was failing to build in Code Engine, failing with a "Class extends value undefined ..." error, which appears to be due to contamination of dependencies.
> Be build fix

- JMS/README.md
- JMS/src/test/java/com/ibm/mq/samples/jms/JmsGetTest.java
- JMS/src/test/java/com/ibm/mq/samples/jms/JmsPutTest.java
1. Added tests for JmsPut and JmsGet
2. Updated readme
> Added tests for JmsPut and JmsGet

- ibm-messaging-mq-cloud-showcase-app/backend/AWS-showcase-backend/models/Responder.js
- ibm-messaging-mq-cloud-showcase-app/backend/AWS-showcase-backend/msms/message-session-manager.js
- Handles the situation when a Requestor puts a message into the queue, following which the backend container goes down, and then it comes back up, resulting in a poison message.
- The logic which I have applied is that when the poison message is consumed, we perform a `MQOPEN` on the `replyToQ` , and if a `MQRC_UNKNOWN_OBJECT` is raised, we know that the reply to queue does not exist anymore, and we can conclude that the message is indeed a poison message.
- I implemented a Promise which resolves to true if the reply to queue exists, else resolves to false. This is then handled in the `Responder` file, where a false value is dealt with a simple output message, and a `resolve(null)` value.
> Poison Message Handler

- amqp-qpid/qpid-quarkus/src/main/java/com/ibm/mq/samples/jms/quarkus/AMQPTestConfig.java
Last quarkus bump missed the setting for `amqp-mqtest.appargs`
> Fix for run mode arguments for quarkus amqp sample

- amqp/Go/README.md
- amqp/Go/amqpConsumer.go
- amqp/Go/amqpProducer.go
- amqp/Go/env.json
- amqp/Go/go.mod
- amqp/Go/go.sum
* Make the parameter parsing more consistent and accurate (no implied defaults which were not being used anyway)
* Use a local env.json file that has only the fields we need: in particular, the AMQP port is not the same as the regular MQ port
* Correct the Consumer so it 
*  works - error handling was wrong previously
* has a receive timeout instead of hanging indefinitely
> Fixes and cleanup on the AMQP Go sample

- Node.js-OTel/Dockerfile.mqapp
- Node.js-OTel/README.md
- Node.js-OTel/admin-password.txt
- Node.js-OTel/app-password.txt
- Node.js-OTel/app.js
- Node.js-OTel/data/action.js
- Node.js-OTel/docker-compose.yaml
- Node.js-OTel/env.json
- Node.js-OTel/instrumentation/control.js
- Node.js-OTel/instrumentation/metrics.js
- Node.js-OTel/instrumentation/span-trace.js
- Node.js-OTel/otels/get-otel.js
- Node.js-OTel/package-lock.json
- Node.js-OTel/package.json
- Node.js-OTel/processors/messages.js
- Node.js-OTel/prometheus/prometheus.yml
- Node.js-OTel/qm.js
- Node.js-OTel/queue-manager/connection.js
- Node.js-OTel/queue-manager/qm-requests.js
- Node.js-OTel/settings/constants.js
- Node.js-OTel/settings/environment.js
- Node.js-OTel/settings/limits.js
HTTP triggered MQI PUT and GET processes sprinkled with Open Telemetry instrumentation.
> New Node.JS Otel samples
